### ISSUE TITLE
Vraag: wat is de reden voor keuze van een `curl` ipv `wp_remote_get` in trait GravityFormsUploadToMediaLibrary functie getFileFromGravityForms

### ISSUE THREAD

**Issue by rmpel** [OpenWebconcept/plugin-openwoo#14]
Hi. 
Vraag: wat is de reden voor keuze van een `curl` ipv `wp_remote_get` in trait GravityFormsUploadToMediaLibrary functie getFileFromGravityForms?

Ik vraag dit omdat we in websites met een htaccess-pre-pass problemen ondervinden met het uploaden van attachments via het GF formulier.

Hiertoe hebben we filters op wp_remote_get en aangelegen functies om daar goed mee om te gaan, echter, door gebruik van `curl` hier worden die filters niet gebruikt en tevens zijn er geen `apply_filters` of `do_actions_ref_array` calls in deze functie, wat ingrijpen eigenlijk onmogelijk maakt.

Daarom dus de vraag :)

Lees het graag.

Remon.

p.s.

vervangende functie is dead-simple, als wp_remote_get gebruikt mag worden;
```
    protected function getFileFromGravityForms(string $url): string
    {
        $result = wp_remote_get( $url );
        return $result && !is_wp_error($result) ? wp_remote_retrieve_body( $result ) : '';
    }
```

**Comment by mvdhoek1** [comment]
Even voor de volledigheid; na contact via de mail in afwachting van de PR. Dit is inderdaad een betere oplossing!
